package npc.entity;

public enum ProfessionType {
  BLACKSMITH, BAKER, FARMER, FISHERMAN, HUNTER, TRADER, MERCHANT, MINER, 
  CARPENTER, PAINTER, POTTER, TAILOR, CHEF, BREWER, WEAVER, ARTIST, 
  MUSICIAN, ACTOR, DOCTOR, PRIEST
}
